### Strings ###########################
ALL_NAME = "TARGET_ALL_USERS"
DEFAULT_SERVER_HOST = "localhost"
DEFAULT_SERVER_PORT = "50000"
DEFAULT_USERNAME_BASE = "User"
SERVER_NAME = "SERVER_NAME_HERE"

### Numbers ###########################
SENDER_MAX_LENGTH = 16
RECIPIENT_MAX_LENGTH = SENDER_MAX_LENGTH
SOCKET_TIMEOUT = 0.05
THREAD_SLEEP_TIME = 0.05
